  function [fil_lo, fil_hi, coeff] = wavefiltercoeff (type)
% function [fil_lo, fil_hi, coeff] = wavefiltercoeff (type)
%
%  calculates lowpass and highpass filter coefficients according
%  to fil_lo(1)*x[k]+ fil_lo(2)*x[k-1]+... etc.
%  To work the function needs a "coeffs.txt" file which contains
%  the coefficients. This file is generated by a function "export_wave.m"
%  which needs the MATLAB-Wavelet toolbox
% 
%  type: determines type of wavelet
%        'db1' ... 'db10' are Daubechies wavelets
%        'sym1' ... 'sym10' are Symmlets
%           'coif1' ... 'coif5' are coiflets
% 
%
% The function wavefiltercoeff is part of the MATLAB toolbox Gait-CAD. 
% Copyright (C) 2010  [Ralf Mikut, Tobias Loose, Ole Burmeister, Sebastian Braun, Andreas Bartschat, Johannes Stegmaier, Markus Reischl]


% Last file change: 26-Nov-2014 11:56:07
% 
% This program is free software; you can redistribute it and/or modify,
% it under the terms of the GNU General Public License as published by 
% the Free Software Foundation; either version 2 of the License, or any later version.
% 
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License along with this program;
% if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110, USA.
% 
% You will find further information about Gait-CAD in the manual or in the following conference paper:
% 
% MIKUT, R.; BURMEISTER, O.; BRAUN, S.; REISCHL, M.: The Open Source Matlab Toolbox Gait-CAD and its Application to Bioelectric Signal Processing.  
% In:  Proc., DGBMT-Workshop Biosignal processing, Potsdam, pp. 109-111; 2008 
% Online available: https://sourceforge.net/projects/gait-cad/files/mikut08biosig_gaitcad.pdf/download
% 
% Please refer to this paper, if you use Gait-CAD for your scientific work.

help = 0;

type_lo=sprintf('%slo',type);
type_hi=sprintf('%shi',type);

f = fopen('Coeffs.txt','r'); 
if f==-1 
   fprintf('Parameterfile ''coeffs.txt'' doesn''t exist'); 
end;
Datei=fread(f); fclose(f);

Zeilen = [0; find(Datei==10)];
for i = 1:length(Zeilen)-1
   coeff(i).name=[];
   coeff(i).value=[];
   Inhalt_Zeile=Datei(Zeilen(i)+1:Zeilen(i+1)-1);
   Elemente= [0; find(Inhalt_Zeile==9); length(Inhalt_Zeile)+1];			% add first and last one
   for j = 1:length(Elemente)-1
      Inhalt_Element=Inhalt_Zeile(Elemente(j)+1:Elemente(j+1)-1)';
      if j==1
      	coeff(i).name=char(Inhalt_Element(1:length(Inhalt_Element)-1));
        	if strcmp(coeff(i).name,type_lo)  
            help = 1; 
         end;
        	if strcmp(coeff(i).name,type_hi) 
            help = 2; 
         end;
     	else
         coeff(i).value=[coeff(i).value str2num(char(Inhalt_Element))];
      end;
      
   end;
   if help == 1 
      fil_lo=coeff(i).value; 
      help = 0;
   end;
   if help == 2 
      fil_hi=coeff(i).value; 
      help = 0; 
   end;
end;      



